//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAuthTest.WSAUTENTICACION {
    using System.Runtime.Serialization;
    using System;
    using System.Threading.Tasks;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthResponse", Namespace="http://schemas.datacontract.org/2004/07/WSAutenticacion")]
    [System.SerializableAttribute()]
    public partial class AuthResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((this.TipoUsuarioField.Equals(value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contrasennaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string identificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido1 {
            get {
                return this.apellido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.apellido1Field, value) != true)) {
                    this.apellido1Field = value;
                    this.RaisePropertyChanged("apellido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido2 {
            get {
                return this.apellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.apellido2Field, value) != true)) {
                    this.apellido2Field = value;
                    this.RaisePropertyChanged("apellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasenna {
            get {
                return this.contrasennaField;
            }
            set {
                if ((object.ReferenceEquals(this.contrasennaField, value) != true)) {
                    this.contrasennaField = value;
                    this.RaisePropertyChanged("contrasenna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identificacion {
            get {
                return this.identificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.identificacionField, value) != true)) {
                    this.identificacionField = value;
                    this.RaisePropertyChanged("identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((this.tipoField.Equals(value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSAUTENTICACION.IAuthService")]
    public interface IAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Login", ReplyAction="http://tempuri.org/IAuthService/LoginResponse")]
        ClienteAuthTest.WSAUTENTICACION.AuthResponse Login(string usuarioCifrado, string contrasennaCifrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Login", ReplyAction="http://tempuri.org/IAuthService/LoginResponse")]
        System.Threading.Tasks.Task<ClienteAuthTest.WSAUTENTICACION.AuthResponse> LoginAsync(string usuarioCifrado, string contrasennaCifrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/RegistrarUsuario", ReplyAction="http://tempuri.org/IAuthService/RegistrarUsuarioResponse")]
        ClienteAuthTest.WSAUTENTICACION.AuthResponse RegistrarUsuario(ClienteAuthTest.WSAUTENTICACION.Usuario nuevoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/RegistrarUsuario", ReplyAction="http://tempuri.org/IAuthService/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<ClienteAuthTest.WSAUTENTICACION.AuthResponse> RegistrarUsuarioAsync(ClienteAuthTest.WSAUTENTICACION.Usuario nuevoUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthServiceChannel : ClienteAuthTest.WSAUTENTICACION.IAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceClient : System.ServiceModel.ClientBase<ClienteAuthTest.WSAUTENTICACION.IAuthService>, ClienteAuthTest.WSAUTENTICACION.IAuthService {
        
        public AuthServiceClient() {
        }
        
        public AuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteAuthTest.WSAUTENTICACION.AuthResponse Login(string usuarioCifrado, string contrasennaCifrada) {
            return base.Channel.Login(usuarioCifrado, contrasennaCifrada);
        }

        public Task<AuthResponse> LoginAsync(string usuarioCifrado, string contrasennaCifrada)
        {
            throw new NotImplementedException();
        }

        public ClienteAuthTest.WSAUTENTICACION.AuthResponse RegistrarUsuario(ClienteAuthTest.WSAUTENTICACION.Usuario nuevoUsuario) {
            return base.Channel.RegistrarUsuario(nuevoUsuario);
        }
        
        public System.Threading.Tasks.Task<ClienteAuthTest.WSAUTENTICACION.AuthResponse> RegistrarUsuarioAsync(ClienteAuthTest.WSAUTENTICACION.Usuario nuevoUsuario) {
            return base.Channel.RegistrarUsuarioAsync(nuevoUsuario);
        }
    }
}
